version: '3.8'
services:
  dynamodb:
    container_name: "localstack_dynamodb"
    build: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=dynamodb
  cache_server:
    build: .
    container_name: cache-server-python
    ports:
      - "8888:8888"
    environment:
      - AWS_ACCESS_KEY_ID=some_key_id
      - AWS_SECRET_ACCESS_KEY=some_secret
      - DOCKER_COMPOSE=true
      - DYNAMODB_HOST=dynamodb
      - DYNAMODB_PORT=4566
      - VT_API_KEY=${VT_API_KEY}
    depends_on:
      - dynamodb
    links:
      - dynamodb
